import os

# Ensure the reports directory exists
SAVE_DIR = "reports"
if not os.path.exists(SAVE_DIR):
    os.makedirs(SAVE_DIR)

def generate_analysis_report(stats_dict, category_df, product_df):
    """Generates a final text-based analytical markdown report."""
    print("\n📝 GENERATING FINAL REPORT...")
    
    # Extracting key insights automatically
    top_category = category_df.iloc[0]['Category']
    top_category_sales = category_df.iloc[0]['Total_Sales']
    top_product = product_df.iloc[0]['Product']
    
    # Formatting the markdown report
    report_content = f"""# DataPulse - Final Analysis Report

## 🏆 Key Business Insights
- **Top Performing Category:** {top_category} (Sales: ₹ {top_category_sales:,.2f})
- **Best Selling Product:** {top_product}

## 📈 Statistical Summary
- **Total Revenue:** {stats_dict['Total Revenue']}
- **Total Items Sold:** {stats_dict['Total Items Sold']}
- **Average Sale Price:** {stats_dict['Average Sale Price']}
- **Highest Single Sale:** {stats_dict['Highest Single Sale']}
- **Lowest Single Sale:** {stats_dict['Lowest Single Sale']}

---
*Report automatically generated by DataPulse Insight Engine.*
"""
    
    # Saving the report
    file_path = os.path.join(SAVE_DIR, "analysis_report.md")
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(report_content)
        
    print(f"[✓] Final report saved successfully at: {file_path}")